Rescue keyword
Shopify/yarp pull request #190
Opened 2023-01-08 21:07 UTC by DmitryTsepelev

Please let me know if tree should be different 🙂

Closes #141.

2023-01-08 21:36 UTC, DmitryTsepelev commented on src/yarp.c
> +        yp_node_t *statements = yp_node_statements_create(parser);
I have to init statements to avoid exception in the generated code but I'll override them down the line 😞Maybe there's a better way to do that

2023-01-08 21:47 UTC, DmitryTsepelev commented
BTW looks like current implementation fails where there's more than one `\n` after statements:

```ruby
begin
  a
  <- it will fail because it expects end here
end
```

Maybe we need a follow up for that

2023-01-10 15:45 UTC, kddnewton requested changes
Looks really good so far! Could you rebase and address a couple of comments?

2023-01-10 15:45 UTC, kddnewton commented on src/yarp.c
> +          expect(parser, YP_TOKEN_KEYWORD_END, "Expected `end` to close `begin` statement.");
You can just use `expect` here, as that will effectively do what you're doing in this switch

2023-01-10 15:45 UTC, kddnewton commented on src/yarp.c
> +          if (accept(parser, YP_TOKEN_NEWLINE) || accept(parser, YP_TOKEN_EQUAL_GREATER)) break;
accept_any will do here

2023-01-10 15:45 UTC, kddnewton commented on config.yml
> +      - name: exception_variable
I'd like to capture the `=>` token as well. In general we try to gather up all of the tokens into _some_ node on the tree.

2023-01-11 17:18 UTC, merged

2023-01-11 17:29 UTC, kddnewton commented
@DmitryTsepelev here's the issue: https://github.com/Shopify/yarp/issues/205