Rescue expression
Shopify/yarp pull request #218
Opened 2023-01-14 11:37 UTC by DmitryTsepelev

It almost works, but returns `CallNode` for all cases, because `=>` is not considered as an assignment. I tried to hack `parse_expression_prefix` to consider `=>` as an assignment too, but looks like it's easier to write a custom function for rescue (cause there are not so many scenarios possible and we're not going to reuse this syntax anywhere). What do you think?

Closes #205

2023-01-21 14:53 UTC, DmitryTsepelev commented
@kddnewton could you please take a look? 🙂

2023-01-26 18:31 UTC, kddnewton commented
I don't think this is quite what we want.

Right now this PR is going to make it so that `foo => bar` is going to parse validly with `bar` being a method call. We don't want this in the general case, only from within the rescue exception. `=>` can't really go into `parse_expression_infix` as a general case.

You _should_ be able to use `parse_expression`, but it's going to need a much higher binding power. Maybe call? I'm not sure. But once you get back the value node, you should be modifying the type of it, similar to how we do when we encounter an `=` sign. You should be able to reuse that logic, just not in that function.

2023-01-26 18:32 UTC, kddnewton requested changes
Marking as request changes.

2023-01-26 20:14 UTC, DmitryTsepelev commented
Updated, looks like changing the type of the node did the trick, thanks!

2023-01-30 20:19 UTC, DmitryTsepelev commented on src/yarp.c
> +          if (assigned_node->as.call_node.receiver == NULL) {
Hm, I might be missing something, but `node` is always a call node, even if it's just `rescue => foo`, node will be `CallNode(nil, nil, IDENTIFIER("ex"), nil, nil, nil, "ex"),`

2023-02-15 17:38 UTC, kddnewton commented on src/yarp.c
> +          if (assigned_node->as.call_node.receiver == NULL) {
You can have something like

```ruby
begin
rescue => @foo
end
```

which is perfectly valid. In this case it'll be an instance variable read node and we'll need to mark it as a write node.

2023-03-04 20:34 UTC, kddnewton commented
This is now done as part of other work. Thanks for the help on this!

2023-03-04 20:34 UTC, closed without merging