Fix parsing empty %w list
Shopify/yarp pull request #407
Opened 2023-03-04 22:30 UTC by DmitryTsepelev

Fixes #402.

Please let me know if I miss something. BTW not related but parse_test freezes on my Mac locally and after a couple of runs computer runs out of memory. Looks like there's a leak somewhere.

2023-03-05 15:53 UTC, kddnewton requested changes

2023-03-05 15:53 UTC, kddnewton commented on src/yarp.c
> +      while (parser->current.type == YP_TOKEN_WORDS_SEP) {
I think there should only be a single token here, so you should be able to do just `accept(parser, YP_TOKEN_WORDS_SEP);` without the look

2023-03-05 20:05 UTC, DmitryTsepelev commented
fixed

2023-03-06 15:30 UTC, kddnewton approved these changes

2023-03-06 15:56 UTC, merged